import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Redis Rate Limiter APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="py-2">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10 border-b">
          Redis Rate Limiter APP
        </h1>
        ;
        <div className="container mx-auto py-3">
          <h1 className="text-3xl font-bold">Redis Rate Limiter APP</h1>;
        </div>
      </main>
    </>
  );
}
