import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rate Limit Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="py-2">
        <>
          <h1 className="text-xl md:text-5xl text-center font-bold py-10 border-b">
            Rate Limit Project
          </h1>
          <div className="container mx-auto py-3"></div>
        </>
      </main>
    </>
  );
}
